"""Monthly CallRail hygiene audit — runs the audit, emails the Excel.

Designed to be invoked by Windows Task Scheduler on the 1st of each month.
Reuses the audit logic from scripts/callrail_hygiene_audit.py and the email
plumbing from scripts/import_report.py.

Usage:
  python scripts/monthly_callrail_audit.py             # Run + email
  python scripts/monthly_callrail_audit.py --no-email  # Generate xlsx only
"""
from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.callrail_hygiene_audit import AUDIT_SQL, classify, name_tokens
from scripts.analyze import query, to_xlsx
from scripts.import_report import send_email


def build_email_html(bucket_counts: dict[str, int]) -> str:
    rows = ""
    bucket_actions = {
        "1. ACTIVE_no_calls_90d": "URGENT — broken tracking on active clients",
        "2. INACTIVE_still_calls": "Leakage — retire CR account or restore client",
        "3. ct_NO_but_has_callrail": "Client marked NOT on CT but CR account still mapped",
        "4. inactive_retire_account": "Cold CR account on inactive client — safe to retire",
        "5. mismatched_label": "CR label doesn't match client name — possible wrong account",
        "6. healthy (reference)": "No action needed",
    }
    for bucket, count in bucket_counts.items():
        if bucket == "Summary":
            continue
        action = bucket_actions.get(bucket, "")
        # Highlight problem buckets in red
        is_urgent = bucket.startswith(("1.", "2.", "3.", "5."))
        color = "#C0392B" if is_urgent and count > 0 else "#2C3E50"
        rows += (
            f"<tr>"
            f"<td style='padding:6px 12px;border-bottom:1px solid #eee;color:{color};font-weight:bold;'>{bucket}</td>"
            f"<td style='padding:6px 12px;border-bottom:1px solid #eee;text-align:right;color:{color};font-weight:bold;'>{count}</td>"
            f"<td style='padding:6px 12px;border-bottom:1px solid #eee;color:#5C6370;'>{action}</td>"
            f"</tr>"
        )

    today = date.today().strftime("%B %Y")
    return f"""
    <html>
    <body style='font-family:Arial,sans-serif;color:#2C3E50;max-width:780px;'>
      <h2 style='color:#1F4E78;margin-bottom:4px;'>CallRail Hygiene Audit — {today}</h2>
      <p style='color:#5C6370;margin-top:0;'>Monthly check on CallRail account health. Full breakdown attached.</p>

      <table style='border-collapse:collapse;margin:16px 0;border:1px solid #ddd;width:100%;'>
        <thead>
          <tr style='background:#1F4E78;color:white;'>
            <th style='padding:8px 12px;text-align:left;'>Bucket</th>
            <th style='padding:8px 12px;text-align:right;'>Count</th>
            <th style='padding:8px 12px;text-align:left;'>Action</th>
          </tr>
        </thead>
        <tbody>
          {rows}
        </tbody>
      </table>

      <p style='color:#5C6370;font-size:12px;'>
        Generated by THMedia Data Hub. Source: <code>scripts/monthly_callrail_audit.py</code>.
        Adjust schedule via Windows Task Scheduler &rarr; <i>THM Data Hub - Monthly CallRail Audit</i>.
      </p>
    </body>
    </html>
    """


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-email", action="store_true")
    args = parser.parse_args()

    print("Querying CallRail audit data...")
    rows = query(AUDIT_SQL)
    print(f"  {len(rows)} CallRail accounts under non-stub clients")

    # Same bucket layout as the manual script
    buckets: dict[str, list[dict]] = {
        "Summary": [],
        "1. ACTIVE_no_calls_90d": [],
        "2. INACTIVE_still_calls": [],
        "3. ct_NO_but_has_callrail": [],
        "4. inactive_retire_account": [],
        "5. mismatched_label": [],
        "6. healthy (reference)": [],
    }
    bucket_to_tab = {
        "ACTIVE_no_calls_90d":      "1. ACTIVE_no_calls_90d",
        "INACTIVE_still_calls":     "2. INACTIVE_still_calls",
        "ct_NO_but_has_callrail":   "3. ct_NO_but_has_callrail",
        "inactive_retire_account":  "4. inactive_retire_account",
        "mismatched_label":         "5. mismatched_label",
        "healthy":                  "6. healthy (reference)",
    }

    def _strip_tz(dt):
        if dt and hasattr(dt, "tzinfo") and dt.tzinfo is not None:
            return dt.replace(tzinfo=None)
        return dt

    for r in rows:
        bucket = classify(r)
        cr_tokens = name_tokens(r.get("callrail_label") or "")
        cn_tokens = name_tokens(r.get("client_name") or "")
        r_out = {
            "client_name": r["client_name"],
            "market": r["market"],
            "status": r["status"],
            "has_call_tracking": r["has_call_tracking"],
            "callrail_label": r["callrail_label"],
            "callrail_company_id": r["callrail_company_id"],
            "calls_90d": r["calls_90d"],
            "calls_total": r["calls_total"],
            "last_call_ever": _strip_tz(r["last_call_ever"]),
            "last_order": _strip_tz(r["last_order"]),
            "name_mismatch": "Y" if cr_tokens and cn_tokens and not (cr_tokens & cn_tokens) else "",
        }
        buckets[bucket_to_tab[bucket]].append(r_out)

    # Summary tab
    summary = [
        {"bucket": "Total CallRail accounts (non-stub clients)", "count": len(rows), "action": ""},
        {"bucket": "", "count": "", "action": ""},
    ]
    for tab, label in [
        ("1. ACTIVE_no_calls_90d", "URGENT — broken tracking on active clients"),
        ("2. INACTIVE_still_calls", "Leakage — retire CR or restore client status"),
        ("3. ct_NO_but_has_callrail", "Stale — CR mapped but client marked NOT on CT"),
        ("4. inactive_retire_account", "Cold — safe to retire in CallRail"),
        ("5. mismatched_label", "CR label doesn't match client name — possible wrong account"),
        ("6. healthy (reference)", "No action needed"),
    ]:
        summary.append({"bucket": tab, "count": len(buckets[tab]), "action": label})
    buckets["Summary"] = summary

    print("\nBucket counts:")
    for k, v in buckets.items():
        print(f"  {k}: {len(v)}")

    out_path = to_xlsx(
        f"CallRail Hygiene Audit {date.today().strftime('%Y-%m')}",
        sheets=buckets,
    )
    print(f"\nWrote: {out_path}")

    if args.no_email:
        return

    bucket_counts = {k: len(v) for k, v in buckets.items() if k != "Summary"}
    html = build_email_html(bucket_counts)
    subject = f"CallRail Hygiene Audit — {date.today().strftime('%B %Y')}"
    send_email(subject, html, attachment_path=out_path)


if __name__ == "__main__":
    main()
